--UC1:
CREATE DATABASE PAYROLL_SERVICE
SELECT * FROM SYS.DATABASES
USE PAYROLL_SERVICE

--UC2:
CREATE TABLE EMPLOYEE_PAYROLL(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(25) NOT NULL,
SALARY FLOAT NOT NULL,
START_DATE DATE NOT NULL)

--UC3:
INSERT INTO EMPLOYEE_PAYROLL VALUES('Elavarasu',10000,'10-05-2022')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Nantha',10000,'2022-05-10')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Sudha',15000,'2018-10-22')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Senthil',20000,'2021-10-05')

--UC4:
SELECT * FROM EMPLOYEE_PAYROLL

--UC5:
SELECT NAME,SALARY FROM EMPLOYEE_PAYROLL WHERE NAME = 'Sudha'
SELECT * FROM EMPLOYEE_PAYROLL WHERE START_DATE BETWEEN '2022-01-01' AND CURRENT_TIMESTAMP

--UC6:
ALTER TABLE EMPLOYEE_PAYROLL ADD GENDER VARCHAR(10) NULL
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Elavarasu'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Nantha'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Sudha'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Senthil'

--UC7:
SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM EMPLOYEE_PAYROLL GROUP BY GENDER