--UC1:
CREATE DATABASE PAYROLL_SERVICE
SELECT * FROM SYS.DATABASES
USE PAYROLL_SERVICE

--UC2:
CREATE TABLE EMPLOYEE_PAYROLL(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(25) NOT NULL,
SALARY FLOAT NOT NULL,
START_DATE DATE NOT NULL)

--UC3:
INSERT INTO EMPLOYEE_PAYROLL VALUES('Elavarasu',10000,'10-05-2022')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Nantha',10000,'2022-05-10')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Sudha',15000,'2018-10-22')
INSERT INTO EMPLOYEE_PAYROLL VALUES('Senthil',20000,'2021-10-05')

--UC4:
SELECT * FROM EMPLOYEE_PAYROLL

--UC5:
SELECT NAME,SALARY FROM EMPLOYEE_PAYROLL WHERE NAME = 'Sudha'
SELECT * FROM EMPLOYEE_PAYROLL WHERE START_DATE BETWEEN '2022-01-01' AND CURRENT_TIMESTAMP

--UC6:
ALTER TABLE EMPLOYEE_PAYROLL ADD GENDER VARCHAR(10) NULL
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Elavarasu'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Nantha'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Sudha'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'M' WHERE NAME = 'Senthil'

--UC7:
SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM EMPLOYEE_PAYROLL GROUP BY GENDER

--UC8:
ALTER TABLE EMPLOYEE_PAYROLL ADD MOBILE DECIMAL NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 9087654321 WHERE NAME = 'Elavarasu'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 9123456780 WHERE NAME = 'Nantha'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 9210876543 WHERE NAME = 'Sudha'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 8907651234 WHERE NAME = 'Senthil'
ALTER TABLE EMPLOYEE_PAYROLL ADD ADDRESS VARCHAR(100) NOT NULL DEFAULT(''), DEPARTMENT VARCHAR(50) NOT NULL DEFAULT('')
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'Thevur',DEPARTMENT = 'Production' WHERE NAME = 'Elavarasu'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'Coimbatore',DEPARTMENT = 'Administration' WHERE NAME = 'Nantha'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'Namakkal',DEPARTMENT = 'IT_Support' WHERE NAME = 'Sudha'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'Dindigul',DEPARTMENT = 'Production' WHERE NAME = 'Senthil'

--UC9:
ALTER TABLE EMPLOYEE_PAYROLL ADD BASIC_PAY FLOAT NOT NULL DEFAULT(0), DEDUCTIONS FLOAT NOT NULL DEFAULT(0),
TAXABLE_PAY FLOAT NOT NULL DEFAULT(0), NET_PAY FLOAT NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 1
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 2
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 15000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 14600 WHERE ID = 3
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 20000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 19600 WHERE ID = 4
